sensors:
  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [-0.372, -1.915, 1.248]
      rpy: [1.56, 1.50, -0.002]
  logical_camera_2:
    type: logical_camera
    pose:
      xyz: [-0.372, -1.155, 1.248]
      rpy: [1.56, 1.50, -0.002]
  logical_camera_3:
    type: logical_camera
    pose:
      xyz: [-0.372, -0.385, 1.248]
      rpy: [1.56, 1.50, -0.002]
  logical_camera_4:
    type: logical_camera
    pose:
      xyz: [-0.372, 0.376, 1.248]
      rpy: [1.56, 1.50, -0.002]
  logical_camera_5:
    type: logical_camera
    pose:
      xyz: [-0.372, 1.142, 1.248]
      rpy: [1.56, 1.50, -0.002]
  logical_camera_6:
    type: logical_camera
    pose:
      xyz: [-0.372, 1.910, 1.248]
      rpy: [1.56, 1.50, -0.002]
  logical_camera_7:
    type: logical_camera
    pose:
      xyz: [1.43, 1.352, 1.288]
      rpy: [-3.141, 1.20, -3.11]
  logical_camera_8:
    type: logical_camera
    pose:
      xyz: [1.43, -0.58, 1.288]
      rpy: [-3.141, 1.20, -3.11]
  break_beam_1:
    type: break_beam
    pose:
      xyz: [1.6, 1.31, 0.91] 
      rpy: [0, 0, 'pi']
  break_beam_2:
    type: break_beam
    pose:
      xyz: [1.6, -0.63, 0.91] 
      rpy: [0, 0, 'pi']
